$schema: "https://json.schemastore.org/github-action.json"
name: "OpenAI Code Review Action"
description: "Executa um code review usando a API da OpenAI e cria uma revisão no PR com comentários inline se houver problemas críticos."

inputs:
  ignore_regex:
    description: "Regex para ignorar arquivos ou diretórios. Exemplo: '.*vendor/.*'. Por padrão, nenhum arquivo é ignorado."
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Checkout do código
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Obter diff do Pull Request
      id: get_diff
      shell: bash
      run: |
        echo "Obtendo diff oficial da PR..."
        DIFF=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" -H "Accept: application/vnd.github.v3.diff" "${{ github.event.pull_request.diff_url }}")
        echo "Diff oficial obtido:"
        echo "$DIFF"
        {
          echo "diff<<EOF"
          printf "%s\n" "$DIFF"
          echo "EOF"
        } >> "$GITHUB_OUTPUT"

    - name: Set GitHub Action Path
      shell: bash
      run: echo "$GITHUB_ACTION_PATH" >> "$GITHUB_PATH"
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}

    - name: Executar Code Review com OpenAI
      id: code_review
      shell: bash
      env:
        IGNORE_REGEX: ${{ inputs.ignore_regex }}
        DIFF_CONTENT: ${{ steps.get_diff.outputs.diff }}
      run: |
        # Escreve o conteúdo do diff (armazenado na variável DIFF_CONTENT) em diff.txt sem interpretar caracteres especiais
        printf '%s\n' "$DIFF_CONTENT" > diff.txt
        # Executa o script code_review.py utilizando o caminho absoluto da action
        # O script receberá o arquivo de diff e o padrão de ignore (pode ser vazio)
        python3 "$GITHUB_ACTION_PATH/code_review.py" diff.txt "$IGNORE_REGEX"
